### ISSUE TITLE
Publish WGS84 coordinates instead of UTM coordinates

### ISSUE THREAD

**Issue by foochuanwei** [mcgill-robotics/ros-interop#19]
The present scheme of publishing UTM coordinates and having another publisher to publish the UTM zone letter and number will be problematic if the UTM coordinates published lie in different UTM zones.

The competition area lies within a UTM zone, so this will not be a problem during competition.

**Comment by anassinator** [comment]
The interop client should be publishing everything relative to the `earth` frame and follow [REP-105](http://www.ros.org/reps/rep-0105.html).

We should also probably consider switching to using [geographic_msgs](http://wiki.ros.org/geographic_msgs).

Finally, since this is a breaking change, we should also provide a migration rule for existing ROS bags (see http://wiki.ros.org/rosbag/migration).

**Comment by anassinator** [comment]
Fixed in #31
